# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_image',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
