# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20191013_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
    ]
